- fix in checking is netforking is up.
Changed files:
    rwhod.init -> 1.4

diff --git a/rwhod.init b/rwhod.init
--- a/rwhod.init
+++ b/rwhod.init
@@ -19,7 +19,10 @@
 [ -f /etc/sysconfig/rwhod ] && . /etc/sysconfig/rwhod
 
 # Check that networking is up.
-[ "${NETWORKING}" = "no" ] && echo "Error: Networking is down" && exit 0
+if [ "${NETWORKING}" = "no" ]; then
+	echo "WARNING: Networking is down. Rwhod service can't be runed."
+	exit 1
+fi
 
 
 # See how we were called.
